### ISSUE TITLE
Train on New Dataset

### ISSUE THREAD

**Issue by LokeSiewWen** [Verg-Avesta/CounTR#42]
Hi, may I know how to train on new Dataset? I am facing this error when trying to input the new dataset. 

Traceback (most recent call last):
  File "/content/CounTR/FSC_finetune_cross.py", line 456, in <module>
    main(args)
  File "/content/CounTR/FSC_finetune_cross.py", line 287, in main
    output = model(samples, boxes, shot_num)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/content/CounTR/models_mae_cross.py", line 206, in forward
    pred = self.forward_decoder(latent, boxes, shot_num)  # [N, 384, 384]
  File "/content/CounTR/models_mae_cross.py", line 174, in forward_decoder
    y = torch.cat(y1,dim=0).reshape(shot_num,N,C).to(x.device)
RuntimeError: shape '[2, 1, 512]' is invalid for input of size 512
Traceback (most recent call last):
  File "/content/CounTR/FSC_finetune_cross.py", line 456, in <module>
    main(args)
  File "/content/CounTR/FSC_finetune_cross.py", line 287, in main
    output = model(samples, boxes, shot_num)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/content/CounTR/models_mae_cross.py", line 206, in forward
    pred = self.forward_decoder(latent, boxes, shot_num)  # [N, 384, 384]
  File "/content/CounTR/models_mae_cross.py", line 174, in forward_decoder
    y = torch.cat(y1,dim=0).reshape(shot_num,N,C).to(x.device)
RuntimeError: shape '[2, 1, 512]' is invalid for input of size 512
[08:42:33.922301] [08:42:33.922375] [08:42:33.922399] [08:42:33.922411] [08:42:33.922425] [08:42:33.922438] [08:42:33.922451] [08:42:33.922477] 

Thanks for your help in advance!

**Comment by Verg-Avesta** [comment]
This seems to be a shape mismatch problem. So if you can ensure that the form and size of the new input dataset are the same as FSC147, there should be no problem.

**Comment by LokeSiewWen** [comment]
Hi, Thanks! Is working now. But I do have a few questions and would like some clarifications from you.

1. Do we need to manually generate the density map?
2. Are they necessary during training? 

![image](https://github.com/Verg-Avesta/CounTR/assets/86844126/d82d1682-a7a2-49a1-ac3e-61f1073afab8)

Thanks for your help in advance! :)

**Comment by Verg-Avesta** [comment]
Yes, I believe it is essential to manually generate density maps, as Gaussian density maps could lead to smaller errors compared to dot annotations.

**Comment by famersalltheday** [comment]
> Hi, Thanks! Is working now. But I do have a few questions and would like some clarifications from you.
> 
> 1. Do we need to manually generate the density map?
> 2. Are they necessary during training?
> 
> ![image](https://private-user-images.githubusercontent.com/86844126/322559252-d82d1682-a7a2-49a1-ac3e-61f1073afab8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ1NTg4NDksIm5iZiI6MTcxNDU1ODU0OSwicGF0aCI6Ii84Njg0NDEyNi8zMjI1NTkyNTItZDgyZDE2ODItYTdhMi00OWExLWFjM2UtNjFmMTA3M2FmYWI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTAxVDEwMTU0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU1MmJkZDE5MTlhOWM2YTc4OGUwODNlODAzMmViMGRjNGE4MDcxODdjZWE5ZTRkZjUwODAyOTAzMWY3MmE5OWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PYWAvxkdxWNpRI-KQxQhilNBZtVKXuTP9E6nZ5OdB6k)
> 
> Thanks for your help in advance! :)

Hi, I was wondering about the process for training new data sets. Is a new dataset file created, or is it a supplement to the original FSC147 file? Because I found out that the annotation.json in FSC147 is read-only, I can't edit it.
