### ISSUE TITLE
AttributeError: 'PosixPath' object has no attribute 'im_dir'. Did you mean: 'is_dir'?

### ISSUE THREAD

**Issue by LokeSiewWen** [Verg-Avesta/CounTR#45]
Hi, May I know how to use the FSC_pretrain.py? because currently I am encountering this error when running this line. 

!python FSC_pretrain.py --epochs 5  --output_dir results/finetune_aug  --resume weights/FSC147.pth --data_path data/fsc/ --anno_file annotations.json --data_split_file train_test_val.json --im_dir images

![image](https://github.com/Verg-Avesta/CounTR/assets/86844126/f8116478-294f-4ee6-bd90-10c609917a3e)

Thank you in advance! :)

**Comment by LokeSiewWen** [comment]
Hi Author @Verg-Avesta , I think I solved this issue.

But I have another question would like your clarification.
In the FSC_pretrain.py, may I know why the density map (.npy) need to be load? If I have another dataset, do I need to generate the .npy file as well?
![image](https://github.com/Verg-Avesta/CounTR/assets/86844126/47face9d-0541-427d-9950-730321c795ff)

Thanks in advance :)

**Comment by Verg-Avesta** [comment]
It's not needed. You can remove that part.

**Comment by zhaigz** [comment]
Hi @LokeSiewWen, I have encountered the same problem. How did you solve it? If I could receive your prompt reply, I would be very grateful.

**Comment by WK0n9** [comment]
Hello, I’m encountering a similar issue while trying to run FSC_pretrain.py. Could you please share how you resolved it? I’d greatly appreciate it!
Traceback (most recent call last):
  File "FSC_pretrain.py", line 364, in <module>
    main(args)
  File "FSC_pretrain.py", line 162, in main
    dataset_train = TrainData()
  File "FSC_pretrain.py", line 120, in __init__
    self.TransformPreTrain = transform_pre_train(data_path)
  File "toPath\CounTR\util\FSC147.py", line 389, in transform_pre_train
    return transforms.Compose([ResizePreTrainImage(args, MAX_HW)])
  File "toPath\CounTR\util\FSC147.py", line 55, in __init__
    super().__init__(args)
  File "toPath\CounTR\util\FSC147.py", line 24, in __init__
    self.im_dir = args.im_dir
AttributeError: 'WindowsPath' object has no attribute 'im_dir'

**Comment by LengNian** [comment]
Hi @WK0n9 , I also have the same problem. I put self.Transformpretrain=transform_pre_train(data_path) has modified self.Transformpretrain=transformpretrain(args).  Hope it can help you.
