### ISSUE TITLE
shape mismatch while running demo.py

### ISSUE THREAD

**Issue by NateshReddy** [Verg-Avesta/CounTR#5]
Traceback (most recent call last):
  File "demo.py", line 198, in <module>
    result = run_one_image(samples, boxes, pos, model)
  File "demo.py", line 126, in run_one_image
    with torch.no_grad():
  File "/home/pdguest/environments/mmdet_new/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/pdguest/natesh/experiment/CounTR/models_mae_cross.py", line 199, in forward
    pred = self.forward_decoder(latent, boxes, shot_num)  # [N, 384, 384]
  File "/home/pdguest/natesh/experiment/CounTR/models_mae_cross.py", line 169, in forward_decoder
    y = torch.cat(y1,dim=0).reshape(shot_num,N,C).to(x.device)
RuntimeError: shape '[3, 1, 512]' is invalid for input of size 1024

I've changed the path for my image and box coordinates with respect to that. I'm not sure what exactly is the cause of error, can you please look into this? thanks

**Comment by Verg-Avesta** [comment]
I think it is the problem of the shot number. The demo.py uses 3 shots and you used 2 shots.
You can change the 3 to the actual shot number (2 in your case) in [here](https://github.com/Verg-Avesta/CounTR/blob/4fa1aa440ca1906c2f1c5ce54e0465ce954b8bb3/demo.py#L118) and [here](https://github.com/Verg-Avesta/CounTR/blob/4fa1aa440ca1906c2f1c5ce54e0465ce954b8bb3/demo.py#L89).
You can try and find whether it is the problem.
